/**
 * Stable typed errors for the encrypted POD workflow.
 * Public messages never include keys, paths, POD contents, or stack traces.
 */

export const POD_ERROR_CODES = [
  "POD_INVALID",
  "POD_TOO_LARGE",
  "POD_FILE_TYPE_REJECTED",
  "POD_SIGNATURE_INVALID",
  "POD_ALREADY_EXISTS",
  "POD_VERSION_CONFLICT",
  "POD_STORAGE_CORRUPT",
  "POD_ENCRYPTION_FAILED",
  "POD_DECRYPTION_FAILED",
  "POD_REVIEW_NOT_ALLOWED",
  "POD_REVIEW_DEADLINE_EXPIRED",
  "POD_CORRECTION_DEADLINE_EXPIRED",
  "SHIPPER_AUTHORIZATION_INVALID",
  "ESCROW_PLAN_BINDING_FAILED",
  "ACTION_ID_CONFLICT",
  "PERSISTENCE_CONFLICT",
  "POD_NOT_FOUND",
  "POD_STATE_INVALID",
  "CARRIER_NOT_WINNER",
  "POD_MANIFEST_MISMATCH",
  "POD_HASH_MISMATCH",
  "POD_KEY_CONFIG",
  "POD_SCAN_REJECTED",
] as const;

export type PodErrorCode = (typeof POD_ERROR_CODES)[number];

export class PodError extends Error {
  constructor(
    readonly code: PodErrorCode,
    message: string,
  ) {
    super(message);
    this.name = "PodError";
  }
}

export const POD_HTTP_STATUS: Readonly<Record<PodErrorCode, number>> = {
  POD_INVALID: 400,
  POD_TOO_LARGE: 413,
  POD_FILE_TYPE_REJECTED: 415,
  POD_SIGNATURE_INVALID: 401,
  POD_ALREADY_EXISTS: 409,
  POD_VERSION_CONFLICT: 409,
  POD_STORAGE_CORRUPT: 500,
  POD_ENCRYPTION_FAILED: 500,
  POD_DECRYPTION_FAILED: 500,
  POD_REVIEW_NOT_ALLOWED: 403,
  POD_REVIEW_DEADLINE_EXPIRED: 409,
  POD_CORRECTION_DEADLINE_EXPIRED: 409,
  SHIPPER_AUTHORIZATION_INVALID: 401,
  ESCROW_PLAN_BINDING_FAILED: 422,
  ACTION_ID_CONFLICT: 409,
  PERSISTENCE_CONFLICT: 409,
  POD_NOT_FOUND: 404,
  POD_STATE_INVALID: 409,
  CARRIER_NOT_WINNER: 403,
  POD_MANIFEST_MISMATCH: 400,
  POD_HASH_MISMATCH: 400,
  POD_KEY_CONFIG: 503,
  POD_SCAN_REJECTED: 422,
};
