/**
 * Stable error vocabulary for the v2 x402 access routes.
 *
 * Responses expose a code, a short safe message, and nothing else: no stack
 * traces, payment payloads, signatures, secrets, private bid fields, or
 * filesystem paths.
 */

export const V2_ACCESS_ERROR_CODES = [
  "TENDER_NOT_FOUND",
  "TENDER_VERSION_MISMATCH",
  "INVALID_LIFECYCLE_STATE",
  "ESCROW_NOT_CONFIRMED",
  "AUCTION_CLOSED",
  "BID_INVALID",
  "BID_INELIGIBLE",
  "PAYMENT_REQUIRED",
  "PAYMENT_INVALID",
  "PAYMENT_RESOURCE_MISMATCH",
  "PAYMENT_AMOUNT_MISMATCH",
  "PAYMENT_ASSET_MISMATCH",
  "PAYMENT_RECIPIENT_MISMATCH",
  "PAYMENT_SCHEME_MISMATCH",
  "PAYMENT_NETWORK_MISMATCH",
  "PAYMENT_SETTLEMENT_FAILED",
  "PAYMENT_CLAIM_CONFLICT",
  "PAYMENT_SETTLEMENT_UNKNOWN",
  "PAYMENT_ALREADY_USED",
  "PAYMENT_RECOVERY_FAILED",
  "RESOURCE_COMMIT_FAILED",
  "PAYMENT_REPLAY",
  "ACTION_ID_CONFLICT",
  "PERSISTENCE_CONFLICT",
  "ACCESS_NOT_CONFIGURED",
  "INTERNAL_ERROR",
] as const;

export type V2AccessErrorCode = (typeof V2_ACCESS_ERROR_CODES)[number];

export class V2AccessError extends Error {
  constructor(
    readonly code: V2AccessErrorCode,
    message: string,
  ) {
    super(message);
    this.name = "V2AccessError";
  }
}

const STATUS: Readonly<Record<V2AccessErrorCode, number>> = {
  TENDER_NOT_FOUND: 404,
  TENDER_VERSION_MISMATCH: 404,
  INVALID_LIFECYCLE_STATE: 409,
  ESCROW_NOT_CONFIRMED: 409,
  AUCTION_CLOSED: 409,
  BID_INVALID: 400,
  BID_INELIGIBLE: 422,
  PAYMENT_REQUIRED: 402,
  PAYMENT_INVALID: 402,
  PAYMENT_RESOURCE_MISMATCH: 402,
  PAYMENT_AMOUNT_MISMATCH: 402,
  PAYMENT_ASSET_MISMATCH: 402,
  PAYMENT_RECIPIENT_MISMATCH: 402,
  PAYMENT_SCHEME_MISMATCH: 402,
  PAYMENT_NETWORK_MISMATCH: 402,
  PAYMENT_SETTLEMENT_FAILED: 402,
  PAYMENT_CLAIM_CONFLICT: 409,
  PAYMENT_SETTLEMENT_UNKNOWN: 503,
  PAYMENT_ALREADY_USED: 409,
  PAYMENT_RECOVERY_FAILED: 503,
  RESOURCE_COMMIT_FAILED: 503,
  PAYMENT_REPLAY: 409,
  ACTION_ID_CONFLICT: 409,
  PERSISTENCE_CONFLICT: 409,
  ACCESS_NOT_CONFIGURED: 503,
  INTERNAL_ERROR: 500,
};

export function v2AccessErrorStatus(code: V2AccessErrorCode): number {
  return STATUS[code] ?? 400;
}
